services:
  mysql:
    image: mysql:8.0
    container_name: cellcentral-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: qlidienthoai
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./QLiDienThoai_mysql.sql:/docker-entrypoint-initdb.d/01-init.sql
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]

  backend:
    build: .
    container_name: cellcentral-backend
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Ho_Chi_Minh
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Ho_Chi_Minh"
      SPRING_PROFILES_ACTIVE: docker

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/qlidienthoai?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456

      BREVO_API_KEY: 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
      BREVO_SENDER_EMAIL: baokhiem02519@gmail.co
      BREVO_SENDER_NAME: CellCentral
      GOOGLE_CLIENT_ID: 689668973954-i6enger07d9dqjpbo7bfn59803s8lksi.apps.googleusercontent.com

volumes:
  mysql_data: