server.port=${PORT:8080}

# ===== JPA / HIBERNATE CONFIG =====
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

# ===== HIKARI CONNECTION POOL =====
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.keepalive-time=60000

# ===== MAIL CONFIG - BREVO API =====
brevo.api-key=${BREVO_API_KEY}
brevo.sender-email=${BREVO_SENDER_EMAIL}
brevo.sender-name=${BREVO_SENDER_NAME:CellCentral}

# ===== GOOGLE LOGIN =====
google.client-id=${GOOGLE_CLIENT_ID:689668973954-i6enger07d9dqjpbo7bfn59803s8lksi.apps.googleusercontent.com}